Feature/xx 2 add city vc
jellocrew/weather_app pull request #1
Opened 2022-06-03 10:03 UTC by jellocrew

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +        tableView.frame = CGRect(x: 0,
Ты тут вручную получается фрейм выставляешь. Этого можно добиться и через констреинты. Во `viewDidLoad`, после того как добавил `tableView` на родительскую, привязывай ее края к краям родительской, или к краям safeArea (разберись что это такое, важный момент) родительской.

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +            LocationManager.shared.findLocations(with: text) { [weak self] locations in
Удобно было бы получать список городов по мере ввода, а не по нажатию на return.

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +        self.navigationController?.popViewController(animated: true)
Я бы вызывал метод `popViewController` в том же классе, где и добавлял его, то есть в MainTableVC. Чтобы вся логика по навигации была в одном месте.
Это было бы удобнее, если в дальнейшем ты изменишь способ показа экрана, например сделаешь его модальным (метод present...).

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        guard let addCityController = self.storyboard?.instantiateViewController(withIdentifier: "AddCityVC") as? AddCityVC else { return }
Тебе не нужен сториборд для создания `AddCityVC`. Ты даже интерфейс там не описываешь. Я бы удалил этот класс из сториборда и создавал бы его в коде, через простой конструктор:
```
let controller = AddCityVC(nibName: nil, bundle: nil)
```

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        self.citiesArray.append(self.emptyCity)
listCitiesArray - массив названий городов, которые добавил пользователь?
citiesArray - массив данных о погоде по городам, которые добавил пользователь?
Так?

Что такое emptyCity и зачем нужен?

citiesArray я бы переименовал во что-то типа `weatherData` или тому подобное, чтобы отражало суть, что это данные о погоде.
Для сохранения listCitiesArray на диск и чтения с диска, я бы сделал отдельный класс, например, CitiesStore, CitiesRepo и тп. С методами get/add/remove и подобными для работы. Смысл в том, чтобы логика по хранению была реализована в отдельном классе.

2022-06-12 14:50 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        self.citiesArray.append(self.emptyCity)
Вообще сделать отдельное хранилище для городов пользователя было бы удобно. Ты бы его использовал на двух экранах - главном и экране добавления города. Логика такая:
- оба класса имеют ссылку на одно и то же хранилище. Оно передается в конструктор класса (лучше) или задается как проперти после создания (хуже).
- при создании MainTableVC, он достает из хранилища список городов и дальше использует как ему нужно
- AddCityVC добавляет выбранный город в общее хранилище
- хранилище умеет рассылать уведомления об обновлениях (через NotificationCenter.default)
- MainTableVC отслеживает уведомления об обновлении данных в хранилище и перестраивает свои данные по такому событию

Таким образом у тебя теряется прямая связь между двумя экранами (что хорошо), каждый из них работает с хранилищем, а не друг с другом.

2022-06-23 21:15 UTC, jellocrew commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +            LocationManager.shared.findLocations(with: text) { [weak self] locations in
Реализовал, но выводит список всех мест а не городов, буду разбираться как отфильтровать. пробовал через GooglePlaces pods, но не дает подключиться к api из за санкций.

2022-06-23 21:16 UTC, jellocrew commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +        self.navigationController?.popViewController(animated: true)
Не совсем понял как это сделать, вызвал метод по другому.

2022-06-23 21:18 UTC, jellocrew commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        guard let addCityController = self.storyboard?.instantiateViewController(withIdentifier: "AddCityVC") as? AddCityVC else { return }
Удалил

2022-06-23 21:21 UTC, jellocrew commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        self.citiesArray.append(self.emptyCity)
Отдельный класс с методами сделал (не уверен то правильно), по отдельному хранилищу в процессе.

2022-06-23 21:27 UTC, jellocrew commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +        tableView.frame = CGRect(x: 0,
constraints программно все задал

2022-06-24 13:56 UTC, dkorneev requested changes

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/Model/CitiesStore.swift
> +    func loadCities() -> Array<String> {
Можно метод loadCIties проще написать. 

И еще хорошей практикой считается выносить константы, чтобы не в двух местах писать строку "listCitiesArray", а написать ее один раз и использовать переменную. Так меньше вероятность ошибки.

```
private let listCitiesArrayKey = "listCitiesArray" 

func loadCities() -> [String] {
    return userDefaults.stringArray(forKey: listCitiesArrayKey) ?? []
}
```

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/Model/CitiesStore.swift
> +class CitiesStore {
Суть уловил правильно. Теперь, при добавлении данных в хранилище, можно рассылать уведомление через NotificationCenter.default, которое ты будешь отлавливать на первом экране и обновлять список добавленных городов.

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +    let fieldheight: CGFloat = 50
👍

Можно аналогичным образом вынести остальные константы для верстки. Это хорошая практика. 
Я сам не всегда так делаю, если честно, но могут на ревью докопаться и вообще нужно стремиться)

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +            if hourNumber > 6 && hourNumber < 9 || hourNumber == 9{
Сложно. Лучше сделать отдельный класс или функцию, в которую ты будешь передавать dayTime и которая будет возвращать значение из энама. Потом ты это значение проверишь в контроллере и настроишь UI как нужно.

```
enum PartOfDay {
    case morning, day, evening, night
}

func getPartOfDay(fromHour hour: Int) -> PartOfDay {
    // TODO: implement
    return .day
}

switch getPartOfDay(fromHour: HOUR_VALUE) {
case .morning:
case .day:
case .evening:
case .night:
}
```

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        let controller = AddCityVC(nibName: nil, bundle: nil)
👍

2022-06-24 13:56 UTC, dkorneev commented on Weather_app_mvvm_test/View/MainTableVC.swift
> +        let controller = AddCityVC(nibName: nil, bundle: nil)
Еще лучше будет смотреться, если ты сделаешь конструктор в AddCityVC, чтобы можно было создавать его так: `let controller = AddCityVC()`, то есть без аргументов.

2022-06-24 14:11 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +        self.navigationController?.popViewController(animated: true)
- Добавляешь в AddCityVC такую проперти: `var onReturn: (() -> Void)?`
- в AddCityVC, вместо `self.navigationController?.popViewController(animated: true)`, вызываешь `onReturn?()`
- в MainTableVC, после создания AddCityVC, присваеваешь его проперти onReturn значение:
```
controller.onReturn = { [weak self] in 
    self?.navigationController?.popViewController(animated: true)
}
```

Разберись зачем нужен [weak self], почитай про циклические ссылки. Вот тут вроде неплохо: https://www.avanderlee.com/swift/weak-self/. На русском тоже можно попробовать поискать.

2022-06-24 14:13 UTC, dkorneev commented on Weather_app_mvvm_test/View/AddCityVC.swift
> +            LocationManager.shared.findLocations(with: text) { [weak self] locations in
Я имел в виду не именно города, а то что есть сейчас, просто не дожидаясь нажатия на return, а сразу после пользовательского ввода. А города это или места не принципиально.

2022-06-24 20:21 UTC, jellocrew commented on Weather_app_mvvm_test/Model/CitiesStore.swift
> +    func loadCities() -> Array<String> {
Да ночью вчера уже писал) нагородил) спасибо за подсказку

2022-06-27 08:40 UTC, dkorneev commented on Weather_app_mvvm_test/Model/GetPartOfDay.swift
> +    func getPartOfDay(fromHour hour: Int) -> PartOfDay {
По-моему тут ошибка, hour используется только один раз.

2022-06-27 08:45 UTC, dkorneev commented on Weather_app_mvvm_test/Model/GetPartOfDay.swift
> +class GetPartOfDay: UIViewController {
Не совсем то, что я имел в виду. 
1. Тебе не нужно наследоваться тут от ViewController.
2. Я бы оставил логику по конфигурированию фона и текста внутри  того места, где этот класс используется. Тогда он у тебя будет отвязан от конкретного экрана и ты его сможешь использовать для разных сценариев по всему приложению. То есть в MainTableVC был бы примерно такой код:
```
        // TODO: fix colors
        let time = GetPartOfDay().getDayTime()
        switch GetPartOfDay().getPartOfDay(fromHour: time) {
        case .morning:
            backgroundColor = .white
            textColor = .black
        case .day:
            backgroundColor = .red
            textColor = .black
        case .evening:
            backgroundColor = .black
            textColor = .black
        case .night:
            backgroundColor = .purple
            textColor = .black
        }
```

А вообще я бы написал как-то так:
```
enum PartOfDay {
    case morning, day, evening, night
    
    static func current() -> PartOfDay {
        switch getDayTime() {
        case 0..<6: return .night
        case 6..<9: return .morning
        case 9..<18: return .day
        case 18..<21: return .evening
        case 21..<24: return .night
        default:
            assertionFailure()
            return .day
        }
    }
    
    static func getDayTime() -> Int {
        let time = NSDate()
        let formatter = DateFormatter()
        formatter.dateFormat = "HH"
        formatter.timeZone = TimeZone.current
        let formatteddate = formatter.string(from: time as Date)
        guard let dayTime = Int(formatteddate) else { return 12}
        return dayTime
    }
}
```

Тогда вызывающий код выглядел бы как-то так: `PartOfDay.current()`

2022-06-27 18:38 UTC, jellocrew commented on Weather_app_mvvm_test/Model/GetPartOfDay.swift
> +class GetPartOfDay: UIViewController {
А если у меня перерисовывается фон и цвет текста во всем приложении, на отдельных экранах фон менять не нужно? есть ли смысл конфигурировать внутри каждой view? или проще получить сразу цвет как я сделал? а при необходимости мы же можем из енама получить данные и сконфигурировать отдельно?

2022-06-27 19:24 UTC, closed without merging

2022-06-28 10:08 UTC, dkorneev commented on Weather_app_mvvm_test/Model/GetPartOfDay.swift
> +class GetPartOfDay: UIViewController {
Это немного разные вопросы.
Смысл выносить код по определению времени дня в отдельный класс в том, чтобы не смешивать эту логику с логикой представления (структура UI, цвета, шрифты и прочее). Если фон нужно менять на каждом отдельном экране, то я бы сделал еще один класс, который бы использовал `PartOfDay.current` и конфигурировал переданную в него вьюху или просто возвращал нужные параметры.